### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by daPhipz**
I edited the README since I could not find an Italian translation anywhere. This German translation is not complete, but it's a good starting point I guess...

Feel free to ping me whenever there are new strings to translate!

### CODE REVIEW

**Comment by ljuzig** [comment]
Hi, many thanks for the German translation, great job! The Italian translation had been temporarily removed a few versions ago, I will add it back shortly! The scripts and translation support were very sketchy and running them could mess up, now they should be ok and usable. I'll merge the pull request now, thanks again!

**Comment by ljuzig** [comment]
I suggest you to shorten this one next time:

```
#: src/memory/memoryMenu.js:248 src/memory/memoryMenu.js:470
msgid "Cached"
msgstr "Zwischengespeicherte Suchdaten lösche"
```

cuz it appears in the context menu and should be as short as possible:
image

**Comment by ljuzig** [comment]
also these ones needed maybe more context and explanation, I will add it to the msgctxt:
```
#: prefs.js:507
msgid "Celsius"
msgstr "Celsius und Fahrenheit bei Temperatursensoren hinzugefügt"

#: prefs.js:508
msgid "Fahrenheit"
msgstr "Celsius"
```

They actually are the content of this dropdown:

image

**Comment by daPhipz** [comment]
Oops, my bad - these should be fuzzy! I used Poedit's feature to pre-translate strings, I guess this slipped through and was not marked as fuzzy.
I will check the translation when I have the time, maybe tomorrow. Sorry!

**Pull request merged**
